### ISSUE TITLE
Lỗi UI (hoặc là cái gì đó tôi không rõ)

### ISSUE THREAD

**Issue by IamsadVN** [dathoangnd/truedevtools.com#2]
![image](https://github.com/dathoangnd/truedevtools.com/assets/112055678/130745a7-9030-4773-afa6-7d91ed8d2d06)

Khi người dùng spam thì sẽ có những cái thông báo trải dài khiến cho tôi thấy khó chịu, chỉ vậy thôi =) (toi khong phai la tre trau, xin dung chui toi)

**Comment by dathoangnd** [comment]
@IamsadVN haha lỗi UI đó ông. Tôi vừa giới hạn chỉ còn 5 message rồi nhé. Do app nó cache khá lâu nên có thể phải clear cache để update.

**Comment by IamsadVN** [comment]
> @IamsadVN haha lỗi UI đó ông. Tôi vừa giới hạn chỉ còn 5 message rồi nhé. Do app nó cache khá lâu nên có thể phải clear cache để update.

![image](https://github.com/dathoangnd/truedevtools.com/assets/112055678/9fe88272-7397-4990-b543-7820beff03f4)
Khoan, cái này bị gì vậy ông, tôi nghĩ nó chỉ là lỗi nhỏ thôi nên không dám tạo 1 issue mới 😓

**Comment by dathoangnd** [comment]
Hiện tại tôi đang dùng code splitting để giảm dung lượng bundle. Mỗi route là 1 chunk nó sẽ load khi chuyển route. Khả năng server quá tải nên nó không load được cái chunk tương ứng. Không biết lỗi này ông có hay gặp không? Nếu có thì tôi sẽ bỏ không code splitting nữa.

**Comment by IamsadVN** [comment]
> Hiện tại tôi đang dùng code splitting để giảm dung lượng bundle. Mỗi route là 1 chunk nó sẽ load khi chuyển route. Khả năng server quá tải nên nó không load được cái chunk tương ứng. Không biết lỗi này ông có hay gặp không? Nếu có thì tôi sẽ bỏ không code splitting nữa.


https://github.com/dathoangnd/truedevtools.com/assets/112055678/7f0e7fc7-b414-479d-83ce-ebcfd41b770b

Có vẻ như tôi spam chuyển các tools nhanh quá thì nó ra như này, mà nếu ông thấy cái này nó không có gọi là quá quan trọng thì có thể bỏ qua :/

**Comment by dathoangnd** [comment]
Chắc không phải do chuyển route nhanh mà ngay lúc đầu nó load thiếu 1 file js nào đó nó mới chết hẳn vầy. Có điều lỗi không ổn định có thể do mạng như thế này rất khó debug và fix. Nếu nhiều người gặp hơn tôi sẽ xem lại. Cảm ơn ông đã feedback.
