### ISSUE TITLE
Text Diff Checker don't compare trailing whitespace

### ISSUE THREAD

**Issue by LeDuyViet** [dathoangnd/truedevtools.com#3]
```123 vs 123                  ``` is same

**Comment by kokoropie** [comment]
I think he trim() every line, LOL
` 123                  ` vs `     123  ` is same
and
```
 123 
123    
```
vs 
```
123
123
```
is same too

**Comment by dathoangnd** [comment]
@kokoropie @LeDuyViet Just fixed it.
Due to caching, you may need to clear cache to update the app on your browser.

![Screenshot 2024-05-04 at 11 02 43](https://github.com/dathoangnd/truedevtools.com/assets/26485062/d14bc263-c99d-4f86-a016-6509259cb47c)

**Comment by kokoropie** [comment]
**Problem solved!**
