### ISSUE TITLE
[Feature Request] Add BCrypt encryption and verification

### ISSUE THREAD

**Issue by davidetestoni** [dathoangnd/truedevtools.com#5]
Hello,

First of all, you did an awesome job!
I often find myself using BCrypt as a password hashing algorithm. When I need to register new users manually in the database while developing the backend, I need to use BCrypt from one of the tools I find online. They also usually allow specifying the number of rounds of encryption to perform.

Would you be considering adding it to the set if tools?

Thank you!

**Comment by dathoangnd** [comment]
@davidetestoni bcrypt tool is now supported. Cheer!

![Screenshot 2024-05-06 at 05 46 05](https://github.com/dathoangnd/truedevtools.com/assets/26485062/af44e2a1-81e7-4082-9313-fecee61b0122)

**Comment by davidetestoni** [comment]
Thank you so much! Have a wonderful week 😃

**Comment by dathoangnd** [comment]
You as well.
