### ISSUE TITLE
[Bug] Markdown Preview: Dark mode for Output is not working properly + Markdown result is not displayed

### ISSUE THREAD

**Issue by vietdm** [dathoangnd/truedevtools.com#7]
Your Operating System:
Your Web Browser:

**This must be done to see the problem**
1. Go to truedevtools.com
2. Use Markdown Preview
3. Check this video evd: https://www.loom.com/share/4d3e1705fab541a6a646bba6cc774f9c

**Comment by dathoangnd** [comment]
@vietdm Mình làm như video bạn gửi nhưng không có lỗi xảy ra
https://www.loom.com/share/ccc413be46f74362874af75efc184359?sid=5d0891d0-18be-4996-8e6c-12f3b00e4135

Bạn có thể tắt bộ gõ tiếng Việt đi xem có phải vấn đề từ bộ gõ không?

**Comment by N-X-T** [comment]
@dathoangnd Góp ý bổ sung tính năng: xem đường dẫn tới thuộc tính của JSON
ví dụ :
`{"name":"Sample Data","description":"This is a sample JSON object","items":[{"id":1,"name":"Item 1","price":10.99,"active":true},{"id":2,"name":"Item 2","price":25.50,"active":false}]}`
khi chọn `active` thì sẽ trả về dạng: `jsonData['items'][0]['active']`

**Comment by vietdm** [comment]
@dathoangnd hi, mình đã thử tắt unikey đi nhưng vẫn gặp trường hợp trên
https://www.loom.com/share/7686c0165f6346d4bf57eeced7109de1

Ngoài ra, khi đang ở chế độ darkmode, area result lại màu trắng => hơi khó chịu mắt 1 chút

**Comment by dathoangnd** [comment]
@vietdm Mình đã cập nhật Markdown Preview trên dark mode sẽ chuyển sang nền đen
Với tool HTML Viewer, mình vẫn giữ nền trắng để tránh xung đột với CSS của code

![Screenshot 2024-05-19 at 09 14 40](https://github.com/dathoangnd/truedevtools.com/assets/26485062/defb47dd-8334-4ebe-a6a2-a5c745934710)

Về việc nó bị xóa preview khi nhập, mình thực sự không có ý tưởng nào rõ ràng về nguyên nhân. Tuy nhiên mình đã thử viết code an toàn hơn một chút. Bạn có thể test lại trên máy bạn xem vấn đề đã được khắc phục chưa?

**Comment by vietdm** [comment]
@N-X-T Mình check lại thì ok rồi. Phần HTML giữ nguyên màu trắng là hợp lý đó. Nhưng mình phải clear cache mới apply dc thay đổi. B cân nhắc thêm version cho file js hoặc css :D

**Comment by dathoangnd** [comment]
Ok mình sẽ cân nhắc. Cảm ơn bạn.
