### ISSUE TITLE
[Feature Request] Full width and half width convertor

### ISSUE THREAD

**Issue by thangtrandn** [dathoangnd/truedevtools.com#9]
Hi,

Thank you so much for your great job! It helps me a lot in my work.

I'm a tester and I often testing with full width and half width character validation in input field.

Would you please consider adding it to the set of tools?

Thank you!

**Comment by dathoangnd** [comment]
Hello @thangtrandn 
Thank you for the suggestion. However, after careful consideration, it seems this tool is not widely popular among developers. So I decided not to proceed on this.

Please let me know if you have other ideas.
